mapentity/urls.py
from django.conf import settings
from django.urls import path, re_path, include

from .registry import registry
from .settings import app_settings
from .views import (map_screenshot, history_delete,
                    ServeAttachment, JSSettings, Convert)

if app_settings['ACTION_HISTORY_ENABLED']:
    from .models import LogEntry


_MEDIA_URL = settings.MEDIA_URL.replace(app_settings['ROOT_URL'], '')
if _MEDIA_URL.startswith('/'):
    _MEDIA_URL = _MEDIA_URL[1:]
if _MEDIA_URL.endswith('/'):
    _MEDIA_URL = _MEDIA_URL[:-1]


app_name = 'mapentity'
urlpatterns = [
    path('map_screenshot/', map_screenshot, name='map_screenshot'),
    path('convert/', Convert.as_view(), name='convert'),
    path('history/delete/', history_delete, name='history_delete'),
    path('api/auth/', include('rest_framework.urls')),
    # See default value in app_settings.JS_SETTINGS.
    # Will be overriden, most probably.
    path('api/settings.json', JSSettings.as_view(), name='js_settings'),
]


if settings.DEBUG or app_settings['SENDFILE_HTTP_HEADER']:
    urlpatterns += [
        re_path(r'^%s/(?P<path>paperclip/.*)$' % _MEDIA_URL, ServeAttachment.as_view()),
    ]


if app_settings['ACTION_HISTORY_ENABLED']:
    from mapentity.registry import MapEntityOptions

    class LogEntryOptions(MapEntityOptions):
        menu = False
        dynamic_views = ['List', ]

    urlpatterns += registry.register(LogEntry, LogEntryOptions)

test_app/urls.py
from mapentity.registry import registry
from test_app.models import DummyModel, MushroomSpot, Road, City

app_name = 'test_app'

urlpatterns = registry.register(DummyModel)
urlpatterns += registry.register(MushroomSpot)
urlpatterns += registry.register(Road)
urlpatterns += registry.register(City)

test_project/urls.py
from django.conf import settings
from django.conf.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include, re_path
from django.contrib import admin
from django.views.generic import RedirectView
from django.views.static import serve
from rest_framework.reverse import reverse_lazy

from test_app.views import DummyDocumentOdt, DummyDocumentWeasyprint
from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('test_app:dummymodel_list'), permanent=True), name='home'),
    path('', include('test_app.urls')),
    path('', include('mapentity.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n')),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': '/'}, name='logout',),

    path('paperclip/', include('paperclip.urls')),
    path('admin/', admin.site.urls),
    path('test/document/dummymodel-<int:pk>.odt', DummyDocumentOdt.as_view(), name="dummymodel_odt"),
    path('test/document/dummymodel-<int:pk>.pdf', DummyDocumentWeasyprint.as_view(), name="dummymodel_pdf"),
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mapentity/views/api.py
import logging

from django.contrib.gis.db.models.functions import Transform
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets, renderers
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework_datatables.filters import DatatablesFilterBackend
from rest_framework_datatables.renderers import DatatablesRenderer

from .. import serializers as mapentity_serializers
from ..decorators import view_cache_latest, view_cache_response_content
from ..filters import MapEntityFilterSet
from ..pagination import MapentityDatatablePagination
from ..renderers import GeoJSONRenderer
from ..settings import API_SRID

logger = logging.getLogger(__name__)


class MapEntityViewSet(viewsets.ModelViewSet):
    model = None
    renderer_classes = [renderers.JSONRenderer,
                        GeoJSONRenderer,
                        renderers.BrowsableAPIRenderer,
                        DatatablesRenderer, ]
    geojson_serializer_class = None
    pagination_class = MapentityDatatablePagination
    filter_backends = [DatatablesFilterBackend, DjangoFilterBackend]
    filterset_class = MapEntityFilterSet

    def get_view_perm(self):
        """ use by view_permission_required decorator """
        return self.model.get_permission_codename('layer')

    def get_serializer_class(self):
        """ Use specific Serializer for GeoJSON """
        renderer, media_type = self.perform_content_negotiation(self.request)
        if getattr(renderer, 'format') == 'geojson':
            if self.geojson_serializer_class:
                return self.geojson_serializer_class
            else:
                _model = self.serializer_class.Meta.model

                class MapentityGeometrySerializer(mapentity_serializers.MapentityGeojsonModelSerializer):
                    class Meta(mapentity_serializers.MapentityGeojsonModelSerializer.Meta):
                        model = _model
            return MapentityGeometrySerializer

        elif getattr(renderer, 'format') == 'datatables':
            # dynamic override of serializer class to match datatable content
            class DatatablesSerializer(mapentity_serializers.MapentityDatatableSerializer, self.serializer_class):
                class Meta(self.serializer_class.Meta):
                    pass
            return DatatablesSerializer
        else:
            return self.serializer_class

    def get_queryset(self):
        """ Transform projection for geojson """
        renderer, media_type = self.perform_content_negotiation(self.request)
        qs = super().get_queryset()
        if getattr(renderer, 'format') == 'geojson':
            return qs.annotate(api_geom=Transform("geom", API_SRID)).defer("geom")
        return qs

    def get_filter_count_infos(self, qs):
        """ Override this method to change count info in List dropdown menu """
        return qs.count()

    @action(detail=False, methods=['get'])
    def filter_infos(self, request, *args, **kwargs):
        """ List of all object primary keys according filters """
        qs = self.get_queryset()
        qs = self.filter_queryset(qs)

        return Response({
            'pk_list': qs.values_list('pk', flat=True),
            'count': self.get_filter_count_infos(qs),
        })

    @view_cache_latest()
    @view_cache_response_content()
    def list(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)

mapentity/views/base.py
import json
import logging
import mimetypes
import os
import re
from datetime import datetime
from io import BytesIO
from urllib.parse import quote

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.gis.db.models import GeometryField
from django.core.exceptions import PermissionDenied
from django.http import (HttpResponse, HttpResponseBadRequest, Http404)
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import static, View
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.views.generic.base import TemplateView
from paperclip.settings import get_attachment_permission, get_attachment_model

from mapentity import models as mapentity_models
from .mixins import JSONResponseMixin, FilterListMixin, ModelViewMixin
from ..decorators import view_permission_required
from ..helpers import capture_image
from ..settings import app_settings

logger = logging.getLogger(__name__)


class ServeAttachment(View):
    def get(self, request, *args, **kwargs):
        """
            Serve media/ for authorized users only, since it can contain sensitive
            information (uploaded documents)
        """
        path = kwargs['path']
        original_path = re.sub(app_settings['REGEX_PATH_ATTACHMENTS'], '', path, count=1, flags=re.IGNORECASE)
        attachment = get_object_or_404(get_attachment_model(), attachment_file=original_path)
        obj = attachment.content_object
        if not hasattr(obj._meta.model, 'attachments'):
            raise Http404
        if not obj.is_public():
            if not request.user.is_authenticated:
                raise PermissionDenied
            if not request.user.has_perm(get_attachment_permission('read_attachment')):
                raise PermissionDenied
            if not request.user.has_perm('{}.read_{}'.format(obj._meta.app_label, obj._meta.model_name)):
                raise PermissionDenied

        content_type, encoding = mimetypes.guess_type(path)

        if settings.DEBUG:
            response = static.serve(request, path, settings.MEDIA_ROOT)
        else:
            response = HttpResponse()
            response[app_settings['SENDFILE_HTTP_HEADER']] = os.path.join(settings.MEDIA_URL_SECURE, path)
        response["Content-Type"] = content_type or 'application/octet-stream'
        if encoding:
            response["Content-Encoding"] = encoding
        if app_settings['SERVE_MEDIA_AS_ATTACHMENT']:
            response['Content-Disposition'] = "attachment; filename={0}".format(
                os.path.basename(path))
        return response


class JSSettings(JSONResponseMixin, TemplateView):
    """
    Javascript settings, in JSON format.
    Likely to be overriden. Contains only necessary stuff
    for mapentity.
    """

    def get_context_data(self):
        dictsettings = {}
        dictsettings['debug'] = settings.DEBUG
        dictsettings['map'] = dict(
            extent=getattr(settings, 'LEAFLET_CONFIG', {}).get('SPATIAL_EXTENT'),
            styles=app_settings['MAP_STYLES'],
        )

        # URLs
        root_url = app_settings['ROOT_URL']
        root_url = root_url if root_url.endswith('/') else '{}/'.format(root_url)
        dictsettings['urls'] = {}
        dictsettings['urls']['root'] = root_url

        from django.db import models
        from mapentity.registry import MapEntityOptions

        class ModelName(mapentity_models.MapEntityMixin, models.Model):
            pass

        options = MapEntityOptions(ModelName)

        dictsettings['urls']['static'] = settings.STATIC_URL
        dictsettings['urls']['layer'] = options.model.get_layer_url()
        dictsettings['urls']['detail'] = '{}modelname/0/'.format(root_url)
        dictsettings['urls']['format_list'] = '{}{}'.format(
            root_url, options._url_path(mapentity_models.ENTITY_FORMAT_LIST)[1:-1]
        )
        dictsettings['urls']['screenshot'] = reverse("mapentity:map_screenshot")

        # Useful for JS calendars
        date_format = settings.DATE_INPUT_FORMATS[0].replace('%Y', 'yyyy').replace('%m', 'mm').replace('%d', 'dd')
        dictsettings['date_format'] = date_format
        # Languages
        dictsettings['languages'] = dict(available=dict(app_settings['TRANSLATED_LANGUAGES']),
                                         default=app_settings['LANGUAGE_CODE'])
        dictsettings['maxCharacters'] = app_settings['MAX_CHARACTERS']
        return dictsettings


class BaseListView(FilterListMixin, ModelViewMixin):
    columns = None
    unorderable_columns = []
    searchable_columns = ['id']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.columns is None:
            # All model fields except geometries
            self.columns = [field.name for field in self.get_model()._meta.fields
                            if not isinstance(field, GeometryField)]
            # Id column should be the first one
            self.columns.remove('id')
            self.columns.insert(0, 'id')

    @view_permission_required()
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@csrf_exempt
@login_required
def map_screenshot(request):
    """
    This view allows to take screenshots, via a django-screamshot service, of
    the map **currently viewed by the user**.

    - A context full of information is built on client-side and posted here.
    - We reproduce this context, via headless browser, and take a capture
    - We return the resulting image as attachment.

    This seems overkill ? Please look around and find a better way.
    """
    try:
        printcontext = request.POST['printcontext']
        assert len(printcontext) < 2048, "Print context is way too big."

        # Prepare context, extract and add infos
        context = json.loads(printcontext)
        selector = context.pop('selector')
        map_url = context.pop('url')
        map_url = request.build_absolute_uri(map_url)
        context['print'] = True
        printcontext = json.dumps(context)
        contextencoded = quote(printcontext)
        map_url += '?context=%s' % contextencoded
        logger.debug("Capture %s" % map_url)

        # Capture image and return it
        width = context.get('viewport', {}).get('width')
        height = context.get('viewport', {}).get('height')

        stream = BytesIO()
        capture_image(map_url, stream, width=width, height=height, selector=selector)
        response = HttpResponse(stream.getvalue(), content_type='image/png')
        response['Content-Disposition'] = 'attachment; filename=%s.png' % datetime.now().strftime('%Y%m%d-%H%M%S')
        return response

    except Exception as exc:
        logger.exception(exc)
        return HttpResponseBadRequest(exc)


@require_http_methods(["POST"])
@csrf_exempt
@login_required
def history_delete(request, path=None):
    path = request.POST.get('path', path)
    if path:
        history = request.session.get('history')
        if history:
            history = [h for h in history if h['path'] != path]
            request.session['history'] = history
    return HttpResponse()

mapentity/views/logentry.py
import django_filters
from django import forms
from rest_framework import serializers
from rest_framework_gis import serializers as gis_serializers

from . import MapEntityViewSet
from .generic import MapEntityList
from ..filters import BaseMapEntityFilterSet
from ..models import LogEntry
from ..registry import registry
from ..serializers import MapentityGeojsonModelSerializer


class LogEntryFilter(BaseMapEntityFilterSet):
    content_type = django_filters.NumberFilter(widget=forms.HiddenInput)
    object_id = django_filters.NumberFilter(widget=forms.HiddenInput)

    class Meta:
        model = LogEntry
        fields = ('user', 'content_type', 'object_id')


class LogEntryList(MapEntityList):
    queryset = LogEntry.objects.order_by('-action_time')
    filterform = LogEntryFilter
    columns = ('id', 'action_time', 'user', 'object', 'action_flag')
    unorderable_columns = ('object', )

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(content_type_id__in=registry.content_type_ids)


class LogEntrySerializer(serializers.ModelSerializer):
    user = serializers.SlugRelatedField('username', read_only=True)
    object = serializers.CharField(source='object_display')
    action_flag = serializers.CharField(source='get_action_flag_display')

    class Meta:
        fields = "__all__"
        model = LogEntry


class LogEntryGeoJSONSerializer(MapentityGeojsonModelSerializer):
    api_geom = gis_serializers.GeometryField(source='geom')

    class Meta(MapentityGeojsonModelSerializer.Meta):
        model = LogEntry
        fields = ('id', )


class LogEntryViewSet(MapEntityViewSet):
    model = LogEntry
    filterset_class = LogEntryFilter
    serializer_class = LogEntrySerializer
    geojson_serializer_class = LogEntryGeoJSONSerializer

    def get_queryset(self):
        qs = self.model.objects.order_by('-action_time')
        return qs.filter(content_type_id__in=registry.content_type_ids)

mapentity/templates/mapentity/_base_navbar.html
{% load static i18n mapentity_tags %}

<nav class="navbar fixed-top navbar-expand-sm navbar-light bg-white">

  <div class="d-flex">
    <ul class="navbar-nav mr-2">
        {% if request.user.is_authenticated %}
        <li class="nav-item {% if viewname == 'list' %}{{ modelname }} active{% endif %}">
          <div id="entitylist-dropdown" class="btn-group">
            <button class="btn-list btn btn-light" onclick="javascript:location='{% url 'home' %}';">
              {% trans "List" %} <span id="nbresults" class="badge badge-secondary"></span>
            </button>
            <button class="btn btn-light dropdown-toggle dropdown-toggle-split"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="sr-only">{% trans "Quick access" %}</span>
            </button>
            <ul class="dropdown-menu">
              {% for entity in allowed_entities %}
                {% if entity.menu %}
                  <li class="dropdown-item {% if entity.modelname == modelname %}active{% endif %}">
                    <a href="{% url entity.url_list %}">
                      <img src="{% static entity.icon_small %}"/> {{ entity.label }}
                    </a>
                    <a class="entitylist-add-btn btn btn-sm btn-success btn-sm" title="{% trans 'Add' %}" href="{% url entity.url_add %}">+</a>
                  </li>
                {% endif %}
              {% endfor %}
            </ul>
          </div>
        </li>
        {% endif %}
      </ul>
  </div>

  <button class="navbar-toggler" type="button"
          data-toggle="collapse" data-target="#navbarToggler"
          aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation history">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarToggler">

    <ul id="historylist" class="navbar-nav {% if request.session.history %} nav-tabs{% endif %}">
      {% block toolbar %}
        {% for item in request.session.history %}
            {% if forloop.first and viewname != "list" %}
                <li class="{{ modelname }} nav-item history first mr-1">
                    <a class="nav-link active" href="{{ item.path }}">
                        <span class="content">{% if title|lower %}{{ title }}{% else %}{{ item.title }}{% endif %}</span>
                        {% if viewname == "detail" %}
                           <button class="close hidden">&times;</button>
                        {% endif %}
                    </a>
                </li>
            {% else %}
                <li class="{% if forloop.first %}{% block nav-detail %}{% endblock nav-detail %}{% endif %} {{ item.modelname }} nav-item history mr-1">
                    <a class="nav-link bg-light" href="{{ item.path }}" title="{{ item.title }}">
                        <span class="content">{{ item.title|truncatechars:12 }}</span>
                        <button class="close d-none">&times;</button>
                    </a>
                </li>
            {% endif %}
        {% endfor %}
      {% endblock toolbar %}
    </ul>

  <ul class="navbar-nav user-menu">
      {% if request.user.is_authenticated %}
      <li class="divider-vertical"></li>
      <li class="dropdown">
        <a href="#" class="nav-link dropdown-toggle bg-light"
          id="navbarDropdownUsermenuLink" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="bi bi-person-fill"></i>
          {{ request.user }}
          {% smart_include "usermenu" %}
        </a>
        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownUsermenuLink">

          {% smart_include "menuentries" %}

          {% if request.user.is_staff %}
          <li class="dropdown-item"><a href="{% url 'admin:index' %}">{% trans "Admin" %}</a></li>
          {% endif %}

          {% if ACTION_HISTORY_ENABLED %}
            {% if 'mapentity.read_logentry' in perms %}
            <li class="dropdown-item">
                <a class="{% block nav-logbook %}{% endblock nav-logbook %}" href="{% url 'mapentity:logentry_list' %}">
                    {% trans "Logbook" %}
                </a>
            </li>
            {% endif %}
          {% endif %}

          <li class="dropdown-divider"></li>
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          {% for language in languages %}
            <li>
              <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}">
                <button type="submit" name="language" value="{{ language.code }}"
                        class="language-menu-item {% if language.code == LANGUAGE_CODE  %}active{% endif %}">
                  {{ language.name_local }} ({{ language.code }})</button>
              </form>
            </li>
          {% endfor %}

          <li class="dropdown-divider"></li>
          <li class="dropdown-item"><a href="{% url 'logout' %}"><i class="bi bi-power"></i> {% trans "Logout" %}</a></li>
        </ul>
      </li>
      {% endif %}
    </ul>

  </div>

</nav>

mapentity/templates/mapentity/_detail_valuelist_fragment.html
{% load i18n %}
{% for v in valuelist %}
    {% if forloop.first %}<ul>{% endif %}
    <li{% if modelname and v.pk %} class="hoverable" data-modelname="{{ modelname }}" data-pk="{{ v.pk }}"{% endif %}>{% if v.enumeration %}<span class="enumeration-value">{{ v.enumeration }}.&nbsp;</span>{% endif %}{{ v.text|safe }}</li>
    {% if forloop.last %}</ul>{% endif %}
{% empty %}
    <span class="none">{% trans "None" %}</span>
{% endfor %}

mapentity/templates/mapentity/_detail_valuetable_fragment.html
{% load i18n %}
{% if records %}
    <table class="table">
        <thead>
            <tr>
            {% for column in columns %}
            <th class="{{ column.name }}">{{ column.text }}</th>
            {% endfor %}
            </tr>
        </thead>
    <tbody>
    {% for record in records %}
        <tr {% if modelname and record.pk %}class="hoverable" data-modelname="{{ modelname }}" data-pk="{{ record.pk }}"{% endif %}>
            {% for attr in record.attrs %}
            <td>
                {% if forloop.first and record.enumeration %}
                  <span class="enumeration-value">{{ record.enumeration }}.&nbsp;</span>
                {% endif %}
                {{ attr|safe }}
            </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% else %}
    <span class="none">{% trans "None" %}</span>
{% endif %}

mapentity/templates/mapentity/base_site.html
{% extends "mapentity/base.html" %}

mapentity/templates/mapentity/logentry_list.html
{% extends "mapentity/mapentity_list.html" %}

{% block mainactions %}{% endblock %}

mapentity/templates/mapentity/mapentity_detail.html
{% extends "mapentity/base_site.html" %}
{% load i18n static mapentity_tags leaflet_tags %}

{% block title %}{{ object }} | {{ block.super }}{% endblock title %}

{% block mainpanel %}
<div class="details-panel detail col-12 col-lg-7 {{ modelname }}">
  <h1 class="details-title">{{ object }}</h1>
  <div class="download-group">
    <div class="btn-group">
      {% block download %}
      {% if mapentity_weasyprint %}
      <a class="btn btn-light btn-sm" rel="noopener noreferrer" target="_blank" href="{{ object.get_document_url }}"><img src="{% static "paperclip/fileicons/pdf.png" %}"/> {% trans "PDF" %}</a>
      {% else %}
      <a class="btn btn-light btn-sm" rel="noopener noreferrer" target="_blank" href="{{ object.get_document_url }}"><img src="{% static "paperclip/fileicons/odt.png" %}"/> {% trans "ODT" %}</a>
      <a class="btn btn-light btn-sm" rel="noopener noreferrer" target="_blank" href="{% url 'mapentity:convert' %}?url={{ object.get_document_url|urlencode }}&to=doc"><img src="{% static 'paperclip/fileicons/doc.png' %}"/> {% trans "DOC" %}</a>
      <a class="btn btn-light btn-sm" rel="noopener noreferrer" target="_blank" href="{% url 'mapentity:convert' %}?url={{ object.get_document_url|urlencode }}"><img src="{% static 'paperclip/fileicons/pdf.png' %}"/> {% trans "PDF" %}</a>
      {% endif %}
      {% endblock download %}
    </div>
  </div>

  <div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="nav-item">
          <a id="tab-properties" class="nav-link active" href="#properties" data-toggle="tab"><i class="bi bi-list-task"></i>
            <span class="d-none d-sm-inline">{% trans "Properties" %}</span>
            {% smart_include "propertiestab" %}
          </a>
        </li>
        {% block before_attachments_extra_tab_nav %}
        {% endblock %}
        <li class="nav-item">
          <a id="tab-attachments" class="nav-link" href="#attachments" data-toggle="tab"><i class="bi bi-file-earmark"></i>
            <span class="d-none d-sm-inline">{% trans "Attached files" %} ({{ object.attachments.count }})</span></a>
        </li>
        {% block after_attachments_extra_tab_nav %}
        {% endblock %}
      {% if ACTION_HISTORY_ENABLED %}
      <li class="nav-item">
        <a id="tab-history" class="nav-link" href="#history" data-toggle="tab"><i class="bi bi-clock-history"></i>
          <span class="d-none d-sm-inline">{% trans "History" %}</span></a>
      </li>
      {% endif %}
      {% if can_edit %}
      <a class="btn btn-primary ml-auto" href="{{ object.get_update_url }}"><i class="bi bi-pencil-square"></i> {% trans "Update" %}</a>
      {% else %}
      <span class="btn disabled ml-auto" href="#"><i class="bi bi-pencil-square"></i> {% trans "Update" %}</span>
      {% endif %}
    </ul>
    <div class="tab-content scrollable">

        <div id="properties" class="tab-pane active show">
          {% block detailspanel %}
          {% include template_attributes %}
          {% endblock detailspanel %}
        </div>
        {% block before_attachments_extra_tab_content %}
        {% endblock %}
        <div id="attachments" class="tab-pane">
          {% block attachmentspanel %}
          {% include 'paperclip/attachment_list.html' with attachment_form_next=object.get_detail_url|add:'?tab=attachments' %}
          {% endblock attachmentspanel %}
        </div>
        {% block after_attachments_extra_tab_content %}
        {% endblock %}
      {% if ACTION_HISTORY_ENABLED %}
      <div id="history" class="tab-pane">
        <table id="logentries-list" class="table table-striped table-bordered">
          <thead>
          <tr>
            <th>{% trans "Date" %}</th>
            <th>{% trans "User" %}</th>
            <th>{% trans "Action" %}</th>
          </tr>
          </thead>
          <tbody>
          {% for logentry in logentries %}
          <tr>
            <td>{{ logentry.action_time }} ({{ logentry.action_time|timesince }})</td>
            <td>{{ logentry.user }}</td>
            <td>{{ logentry.action_flag_display }}{% if logentry.change_message %} - {{ logentry.change_message }}{% endif %}</td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="3">{% trans "None" %}</td>
          </tr>
          {% endfor %}
          {% if logentries_hellip %}
          <tr>
            <td>&hellip;</td>
            <td>&hellip;</td>
            <td>&hellip;</td>
          </tr>
          {% endif %}
          </tbody>
        </table>
        {% if 'mapentity.read_logentry' in perms %}
        <a href="{% url 'mapentity:logentry_list' %}?content_type={{ object.get_content_type_id }}&object_id={{ object.pk }}" class="btn btn-light">
            {% trans "Full history" %}
        </a>
        {% endif %}
      </div>
      {% endif %}
    </div>
  </div>
</div><!-- col-md-7 -->

<div class="splitter"></div>

<div class="map-panel detail col-12 col-lg-5" {% if mapwidth and mapheight %}style="width: {{ mapwidth }}px; height: {{ mapheight }}px;"{% endif %}>
  {% block mappanel %}
  {% if object.get_geom %}
  {% include "mapentity/mapgeometry_fragment.html" with mapname="detailmap" %}
  {% else %}
  <p class="nomap">{{ empty_map_message }}</p>
  {% endif %}
  {% endblock mappanel %}
</div><!-- col-md-5 -->

{% endblock mainpanel %}
{% block extrabody %}
  {{ block.super}}
  <script type="text/javascript" src="{% static 'mapentity/mapentity.detail.js' %}"></script>
{% endblock %}

mapentity/templates/mapentity/mapentity_detail_attributes.html
{% load mapentity_tags %}

{% block attributes %}
    {% smart_include "detail" %}
{% endblock attributes %}

mapentity/templates/mapentity/mapgeometry_fragment.html
{% load i18n static mapentity_tags leaflet_tags %}

<div id="{{ mapname }}"
     data-fitmaxzoom="{{ MAP_FIT_MAX_ZOOM }}"
     data-mapextent="{{ object|latlngbounds }}"
     data-readonly="{% if readonly %}readonly{% endif %}" data-feature-url="{{ object.get_layer_detail_url }}">
</div>
{% leaflet_map mapname fitextent=False creatediv=False %}